<?php
    session_start();
    $user = user::identify();
    
    $theme = new theme();
    $page = new page();
    $page = page::dispatch();
    $theme->load('header');
    $theme->load('header_content');
    
?>

<div id="main" role="main">

    <div class="width_setter">
    <div id="content_holder">

        <div class="column66">
            <h2>Terms and Conditions</h2>
            
            <p>These Terms and Conditions ("Terms and Conditions") set forth the terms and conditions for an individual ("you" or "Member") to participate in LifeStories.com or SpiritualLifeStories.com (the "Program" or the "Website" or "the platform"). The Program is owned and operated by LifeStories.com, LLC and its subsidiaries and affiliates (collectively, "LSC", "us", "our," "company," or "we").&nbsp; The Program includes the website <a href="http://www.LifeStories.com">www.LifeStories.com</a> and <a href="http://www.SpiritualLifeStories.com">www.SpiritualLifeStories.com</a> as well as certain mobile applications and mobile websites (collectively, the "Website").</p>
            
            <p>Participation in the program is limited to individuals residing in the United States and elsewhere who are at least eighteen (18) years of age.&nbsp; Participation in the Program and its benefits are offered at the sole discretion of LSC and LSC reserves the right to deny or revoke the participation of any individual(s) or Members at any time and for any or no reason.&nbsp;</p>
            
            <p>By enrolling or participating in the Program, using the Website, using any of our other services or clicking on "I agree to the Terms and Conditions," you agree that you have read, understand and agree to these Terms and Conditions, our&nbsp;Privacy Policy&nbsp;and any additional terms or conditions applicable to any programs or services in which you may participate as part of the Program, as any of the same may be modified and exist from time to time.&nbsp; We reserve the right in our sole discretion to cancel, change, modify, limit, suspend or discontinue any of the Terms and Conditions other aspects of the Program, regulations, benefits, conditions of participation, procedures, restrictions, in whole or in part at any time, all without notice or liability and even though such actions may affect any aspects of this website. You will be bound by any such actions.</p>
            
            <p>By signing up for an account, a Member may wish to invite others ("Invitee") via an email request sent to Invitee to read/add content to a Member's book.&nbsp; If Invitee accepts and Invitee also registers for an account, said Invitee will be able to see Members questions and answers and pictures in that specific book.&nbsp; As well, this Invitee will be able to have access to Member's entire book in the library section titled "Your Friends Books".&nbsp; Member will have the ability to invite Invitees to each book in his/her Library.</p>
            
            <p>Any changes to these Term and Conditions will be shown in the Terms and Conditions on the website,<a href="http://www.lifestories.com">www.lifestories.com</a> or at www.spirituallifestories.com and will be effective immediately unless stated otherwise.&nbsp; A notice that a change has been made will be posted on the LifeStories.com website.</p>
            
            <p>If you do not agree to these Terms and Conditions, please do not participate in the Program, access or use the Website, use any of our programs or services or otherwise interact or communicate with us.</p>
            
            <p><strong>Program Participation</strong></p>
            
            <p>Upon your enrollment in the Program, we will establish an account in your name ("Account"). Any transfer in violation of these Terms and Conditions is void.&nbsp; If you (i) violate these Terms and Conditions, (ii) commit fraud or falsify information in connection with your Account, your use of the Program, our services or the Website, (iii) take any other action detrimental to the Program, other Members, <b>WE MAY WITHOUT AFFECTING OUR OTHER RIGHTS TERMINATE YOUR ACCOUNT, AND YOU WILL FORFEIT ANY ACCESS TO THIS WEBSITE.</b>You may elect to close your Account, terminate your participation in the Program and/or not use our products and services, in each case, at any time in your sole discretion.<b>UPON CLOSURE OF YOUR ACCOUNT FOR ANY REASON ACCESS AND DATA INPUTTED (CONTENT TO QUESTIONS, ANSWERS TO QUESTIONS AND PICTURES ADDED OR ANY OTHER MATERIAL THAT MEMBER ADDED/INPUTTED/UPLOADED TO SITE) BECOME VOID AND CANNOT BE RETREIVED.</b></p>
            
            <p>If website is charging your card for access, &nbsp;LSC will credit your credit card monthly at the established fee. We are not responsible if a Member delays or fails to enable or disable a credit card or lets one become void.&nbsp; We are not responsible if a Member delays or fails to make adjustments to his/her Account regarding disputed claims.&nbsp; We may also cancel assess if Member does not pay the credit card company owed to us.</p>
            
            <p>If you believe that Member payment error has occurred, you must notify us a <a href="http://www.lifestories.com">www.lifestories.com</a> or www.spirituallifestories.comwithin sixty (60) days of the date of payment due. You may be required to contact your credit card company to discuss issues regarding this matter than may arise.</p>
            
            <p>In the case of any violation of these Terms and Conditions or any other fraud or action detrimental to the Program, including but not limited to your engaging in a pattern of abuse or in any matter that as determined by us in our sole discretion, we reserve the right to make any adjustments to your Account at any time and to take appropriate administrative or legal action. In such a case, some or all of your data/content added may be forfeited and/or your Account closed, and we reserve the right to seek reimbursement from you for any funds that may have already been redeemed as well as any administrative or legal costs.</p>
            
            <p>LSC shall not be liable for any delay or failure in receiving information from Member.</p>
            
            <p>In LSC's sole discretion, LSC may replace a lost account and all data if ONLY within the 60 days period after credit card has been cancelled or Member willingly stops credit card payment.&nbsp; LSC reserves the right to deny or limit or impose conditions upon requests for such replacement of data and shall have no liability for any failure or delay in doing so.</p>
            
            <p>LSC does not represent, warrant or guarantee that any aspect of the websites will always work properly and website may go down and Member data inputted/content/pictures may be lost.&nbsp; <a href="http://www.LifeStories.com">www.LifeStories.com</a> and <a href="http://www.SpiritualLifeStories.com">www.SpiritualLifeStories.com</a> may become damaged or be defective and there may be times when the participating members are unable to accept or process any or all web site activity.&nbsp; LSC shall have no liability for any failure or inability of any Member to access these website.&nbsp; In the event of the failure or inability of any Member to use a these website, please contact LifeStories.com or SpiritualLifeStories.com</p>
            
            <p>Customer will be billed on their selected credit card determined at sign-up on a monthly basis and for each month they are willing an active Member.</p>
            
            <p><strong>Member Obligations</strong></p>
            
            <p>You agree that you will not, and will not permit others to: (i) provide any purposely inaccurate information, commit fraud or falsify information in connection with your Account; (ii) provide any unauthorized third party with access to the Program or any information, data, text, links, images, software, chat, communications or other content proprietary to LSC (collectively, "Content"); (iii) modify, reverse engineer, reverse assemble or decompile any of the software applications used by you in connection with your participation in the Program; (iv) engage in any activity that does not comply with applicable laws and regulations (including federal, state and local laws and regulations) or otherwise engage in any illegal, manipulative or misleading activity through the use of the &nbsp;Program; (v) introduce into the Website any code intended to disrupt the Program or Website, alter or delete its Content, access confidential Content on the Website or interfere with the operation of the Program, including, but not limited to, distribution of unsolicited advertising or mail messages and propagation of computer worms and viruses; (vi) attempt to access any data not intended for you or attempt to scan or test the security or configuration of the Website or to breach security or authentication measures without proper authorization; (vii) post any material on the Website or within the Program that is defamatory, obscene or otherwise unlawful or violates any third party's right of privacy or publicity; or (viii) infringe any third party's patent, copyright, service mark, trademark or other intellectual property right of any kind or misappropriate the trade secrets of any third party in connection with your use of the Program or the Website, or (ix) otherwise act in a fraudulent, illegal, malicious or negligent manner when using the&nbsp; program or the&nbsp; Website. You may post reviews, comments, photos, and other content; make other communications; and submit suggestions, ideas, comments, questions, or other information, as long as the content is in compliance with the rules and conventions for postings and not illegal, obscene, threatening, defamatory, invasive of privacy, infringing of intellectual property rights, or otherwise injurious to third parties or objectionable and does not consist of or contain software viruses, political campaigning, commercial solicitation, chain letters, mass mailings, or any form of "spam." You may not use a false e-mail address, impersonate any person or entity, or otherwise mislead as to the origin of any content.</p>
            
            <p>If you do post content or submit information or material to the Website, Linked Websites, through social media accounts administered by LSC, through email directed to us, or through other communications, and unless we indicate otherwise, you grant LSC a nonexclusive, royalty-free, perpetual, irrevocable, and fully sublicensable right to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, and display such content throughout the world in any media. You grant LSC the right to use the name that you submit in connection with such content, if we choose. You represent and warrant that you own or otherwise control all of the rights to the content that you post; that the content is accurate; that use of the content you supply does not violate these Terms and Conditions and will not cause injury to any person or entity.</p>
            
            <p>LSC has the right but not the obligation to monitor and edit or remove any activity or content. LSC takes no responsibility and assumes no liability for any content posted by you or any third party.</p>
            
            <p><strong>LSC Website</strong></p>
            
            <p>LSC grants you a limited license to access and make personal use of the Website. This license does not include any right to resell or make commercial use of the Website or its contents. The Website and its content may not be reproduced, duplicated, copied, sold, resold or otherwise exploited for any commercial purposes without the express written consent of LSC.</p>
            
            <p>LSC cannot and does not guarantee continuous, uninterrupted or secure access to the Website. You acknowledge that there may be interruptions in service or events that are beyond our control. The Website may be unavailable from time to time for a variety of reasons including, without limitation, routine maintenance.&nbsp; We retain the right in our sole discretion to deny service or access to the Website to anyone at any time and for any reason.</p>
            
            <p>Certain parts of the Website will be password protected and accessible only to users with valid usernames and passwords.&nbsp; You are the only individual authorized to use your password.&nbsp; Any transfer of passwords to, or use of passwords by, an unauthorized person is strictly prohibited.&nbsp; You will maintain the confidentiality of the user IDs and passwords by which you access the Program and the Website, and will allow access to the Program and the Website only by authorized persons, and not by any program, expert system, electronic agent, "bot" or other automated means. You acknowledge that neither LSC nor any third party associated with the Program will contact you to solicit your user ID or password. Therefore, you should not provide your user ID or password to any person whom you do not authorize to use your Account. Any use of your assigned user IDs or passwords will be deemed to be your use. Remember to choose a strong password, including numbers, capital letters, special characters, etc., and one that is not typically found in a dictionary. You may never use someone else's Account, username or password without that person's permission. When creating your Account, you must provide accurate and complete information. YOU ARE RESPONSIBLE FOR MAINTAINING THE CONFIDENTIALITY OF YOUR PASSWORD AND ACCOUNT, AND YOU AGREE THAT YOU ARE FULLY RESPONSIBLE FOR ALL ACTIVITIES THAT OCCUR UNDER YOUR PASSWORD OR ACCOUNT; AND THAT LSC HAS NO LIABILITY FOR ANY ACTIVITIES THAT OCCUR UNDER YOUR PASSWORD OR ACCOUNT.&nbsp; If there is a breach of security involving your Account, you must immediately change your password and notify us of such breach.&nbsp; You agree that, unless you have first notified us immediately of any such breach, we should assume that any instruction transmitted using your user ID and password is yours and has been authorized by you, and we will have no obligation to inquire into the propriety of such instruction.</p>
            
            <p>The Website provides hyperlinks, which are highlighted words or pictures within a hypertext document that, when clicked, take you to other websites not controlled by us ("Linked Websites"). These Linked Websites may contain terms and conditions and privacy provisions that are different from those provided herein. In addition, if you use a social media platform or your mobile device or other method of communication to interact with LSC or the Website, these applications also have terms and conditions and privacy provisions that govern the use of personal information related to that application. We are not responsible for the content, operation, actions or omissions of any Linked Website nor for the collection, use or disclosure of information collected through Linked Websites, social media platforms, mobile devices or other methods of communication and we expressly disclaim any and all liabilities related to such matters.</p>
            
            <p><strong>Ownership and Trademarks</strong></p>
            
            <p>LSC, or the applicable third party owner, retains all right, title and interest in, to and under all patents (including all reissues, divisions, continuations and extensions of such patents), patent applications, trademarks, trademark registrations, service marks, trademark registration applications, tradenames, domain names, all other names and slogans embodying business, product or service goodwill, copyrights, computer software, specifications, data, designs, trade secrets, technology, diagnostic tools, inventions, know-how, processes and confidential and proprietary information and any other intellectual property or other right, in all information and content (including all text, data, graphics, and logos) in the Program and on the Website. LSC may enforce all rights to the full extent of the law.</p>
            
            <p>Without the prior written consent of LSC, you are strictly prohibited from modifying, copying, transmitting, distributing displaying, performing, reproducing, publishing, licensing, framing, creating derivative works from, transferring or otherwise using in any other way for commercial or public purposes, in whole or in part, any information, text graphics, images, video clips, directories, databases, listing or software obtained from the Program or the Website. Systematic retrieval of content from the Website to create or compile, directly or indirectly, a collection, compilation, database or directory (whether through robots, spiders, automatic devices or manual processes) or creating links to the Website without written permission from LSC is strictly prohibited.</p>
            
            <p>Nothing in the Program or on the Website shall be interpreted as granting any license or right to use any image, trademark, logo or service mark in the Program or on the Website. Unless otherwise specified, the Website is for your personal and non-commercial use only and you may print, copy and download any information or portion of the Website for your personal use only. Copying or downloading material from the Website does not transfer title to any material on the Website to you. If you copy or download any information or software from the Website, you agree that you will not remove or obscure any copyright or other notices or legends contained in any such information. You are prohibited from using any marks for any purpose including, but not limited to, use as metatags on other pages or sites on the World Wide Web without the written permission of LSC or such third party, which may own the marks.</p>
            
            <p>You will not upload, post or otherwise make available on the Website any material protected by copyright, trademark or other proprietary right without the express permission of the owner of the copyright, trademark or other proprietary right.</p>
            
            <p>You recognize the value of the goodwill associated with the Program and acknowledge that the Program and the Website and all rights therein and goodwill pertaining thereto belong exclusively to LSC. You further agree that it is critical that such goodwill be protected and enhanced and, toward this end, you shall not during the term of your membership in the&nbsp;Program or thereafter: (i) attack the title or any rights of LSC or related to the copyright, trademarks, patents and other intellectual property in the Program and /or the&nbsp;Website; (ii) attack the validity of these Terms and Conditions; (iii) do anything by action or omission which might impair, violate or infringe the copyright, trademarks, patents, and other intellectual property in the Program and/or the Website; (iv) claim (adversely to LSC or anyone claiming rights through LSC) any right, title or interest in or to the copyright, trademarks, patents and other intellectual property in the Program and/or the Website; (v) misuse or harm the copyright, trademarks, and other intellectual property in the Program and/or the Website or bring the Program into disrepute; (vi) for your benefit, directly or indirectly, register or apply for registration of LSC's trademarks or any mark which is, in LSC's opinion, the same as or confusingly similar to any of LSC's trademarks; and/or (vii) for your benefit, directly or indirectly, register, maintain or apply for registration of a domain name which is, in LSC's opinion, the same as, confusingly similar to or incorporates any of the LSC's trademarks.</p>
            
            <p><strong>Communications</strong></p>
            
            <p>We may send you certain Program information that could include: (i) information regarding your Account and other information necessary for Program administration; (ii) promotional communications which will inform you of special offers and products we believe might be of interest to you; and (iii) promotional communications from third parties that have a relationship with the Program. &nbsp;As a member in the Program, you have consented to receive all of the kinds of information described above. If, at any time, you wish to no longer receive promotional communications relating to the Program, you may opt-out of the receipt of such promotional communications by clicking on the opt-out link provided at the bottom of each e-mail.&nbsp; Requests to be unsubscribed or to opt out of promotional communications will be processed promptly, however you may be included in the selection for additional promotional communications for a short period of time after you make your request. We reserve the right to send out certain communications relating to Program information and other Program administration messages, without offering you the opportunity to opt out of receiving them.</p>
            
            <p><strong>Collection and Use of Certain Information</strong></p>
            
            <p>You acknowledge that in order to operate the Program/Website, we will collect information about you, your participation in the Program and your activities. You agree to hold us harmless for any information so disclosed to us.</p>
            
            <p>You authorize us to use any such information and to disclose such information (i) to our representatives and agents in order to administer the website, (ii) to third parties, where necessary or convenient for transfer or redemption requested information such as printing of your book in connection with the Program/Website, and (iii) otherwise in accordance with the terms of the&nbsp;Privacy Policy.</p>
            
            <p><strong>Disclaimers</strong></p>
            
            <p>ALL SUCH TRANSACTIONS AND BEHAVIORS ARE SUBJECT TO ALL APPLICABLE LAWS AND THE TERMS AND CONDITIONS SET BY THE COMPANY AND IT'S PARTNERS, SUBSIDIARIES, ETC.&nbsp;</p>
            
            <p>THE INFORMATION, PRODUCTS AND SERVICES PROVIDED AS PART OF THE PROGRAM AND ON THE WEBSITE AND OTHERWISE ARE PROVIDED ON AN "AS IS," "WHERE IS" AND "WHERE AVAILABLE" BASIS. LSC DOES NOT WARRANT THE INFORMATION OR SERVICES PROVIDED AS PART OF THE PROGRAM OR YOUR USE OF THE WEBSITE GENERALLY, EITHER EXPRESSLY OR IMPLIEDLY, FOR ANY PARTICULAR PURPOSE AND EXPRESSLY DISCLAIMS ANY IMPLIED WARRANTIES, INCLUDING BUT NOT LIMITED TO, WARRANTIES OF TITLE, NON-INFRINGEMENT, ABILITY OR FITNESS FOR A PARTICULAR PURPOSE. LSC WILL NOT BE RESPONSIBLE FOR ANY LOSS OR DAMAGE THAT COULD RESULT FROM INTERCEPTION BY THIRD PARTIES OF ANY INFORMATION OR SERVICES MADE AVAILABLE TO YOU VIA THE WEBSITE. ALTHOUGH THE INFORMATION PROVIDED TO YOU ON THE WEBSITE IS OBTAINED OR COMPILED FROM SOURCES WE BELIEVE TO BE RELIABLE, LSC CANNOT AND DOES NOT GUARANTEE THE ACCURACY, VALIDITY, TIMELINESS OR COMPLETENESS OF ANY INFORMATION OR DATA MADE AVAILABLE TO YOU FOR ANY PARTICULAR PURPOSE. LSC SHALL NOT BE LIABLE FOR ANY FAILURE OF THE PROGRAM, OUR SERVICES OR THE WEBSITE ARISING OR RESULTING FROM ACTS OR EVENTS BEYOND LSC'S CONTROL.</p>
            
            <p><strong>Limitation of Liability</strong></p>
            
            <p>NEITHER WE, OUR AFFILIATES NOR ANY OF OUR OR THEIR RESPECTIVE OFFICERS, DIRECTORS, SHAREHOLDERS, MEMBERS, OWNERS OR PARTNERS HAVE ANY RESPONSIBILITY OR LIABILITY FOR ANY EXPENSE, LOSS, COST, INJURY, DAMAGE, DELAY, ACCIDENT OR ANY OTHER MATTER OR THING WHATSOEVER (COLLECTIVELY, "COSTS"), HOWEVER SUFFERED OR CAUSED (INCLUDING COMPENSATORY, INCIDENTAL, INDIRECT, SPECIAL, PUNITIVE, CONSEQUENTIAL OR EXEMPLARY DAMAGES OR DAMAGES FOR LOSS OF INCOME OR PROFITS), DIRECTLY OR INDIRECTLY ARISING OUT OF OR RELATED TO (I) THE&nbsp; PROGRAM OR YOUR PARTICIPATION IN THE&nbsp; PROGRAM; (II) ANY FAILURE, DELAY OR DECISION BY US IN ADMINISTERING THE&nbsp; PROGRAM OR AMENDING THESE TERMS AND CONDITIONS (III) UNAUTHORIZED USE OF YOUR ACCOUNT (IV) ANY PRODUCT, SERVICE, OFFER, REPRESENTATION, STATEMENT OR CLAIM ABOUT THE&nbsp; PROGRAM MADE BY A PARTICIPATING MEMBER OR ANY OTHER PERSON; OR (V) THE PURCHASE, REDEMPTION FOR OR USE OF ANY GOODS OR SERVICES OF PARTICIPATING MEMBERS. THIS APPLIES EVEN IF WE OR OUR REPRESENTATIVES ARE ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.&nbsp; THE MEMBER'S EXCLUSIVE REMEDY SHALL BE LIMITED TO THE ISSUANCE OF THE IMPROPERLY DENIED AND LSC SHALL HAVE NO OTHER LIABILITY.</p>
            
            <p><strong>General</strong></p>
            
            <p>The Terms and Conditions constitute the entire agreement between you and us regarding your participation in the Program, and your ability to obtain any other services or benefits of the Program.&nbsp; Interpretation of these Terms and Conditions shall be at the sole discretion of LSC.&nbsp; Except as expressly provided herein, LSC reserves all rights with respect to the Program and the Website, and may pursue all legally available options under both civil and criminal laws (and may cooperate with law enforcement agencies and notify your Internet Service Provider of any fraudulent activity we associate with your use of the Website) in the event of any violations. When you deal with us over the Internet, you consent to the formation of contractual relations through electronic communications. We are the final authority as to the interpretation of these Terms and Conditions and as to any other questions or disputes regarding the Program. The Program and these Terms and Conditions are governed by the laws of the State of Texas. If any provision of the Terms and Conditions is invalid or unenforceable, such provision shall not affect the validity and enforceability of the remaining Terms and Conditions. No waiver by LSC of any breach or default or failure to exercise any right allowed under the Terms and Conditions is a waiver of any preceding or subsequent breach or default or a waiver or forfeiture of any similar or future rights under the Terms and Conditions.</p>
            
            <p>The Website is controlled from offices within the United States. LSC makes no representation that the Program, the services provided by us or the content or materials in the Website are appropriate or available for use in all jurisdictions. Access to the Program, the services provided by us or the Website content or materials from jurisdictions where such access is illegal is strictly prohibited. If you choose to use the Program, to use the services provided by us or to access the Website from other jurisdictions, you do so at your own risk. You are always responsible for your compliance with applicable laws.</p>
            
            <p><strong>Indemnification and Release</strong></p>
            
            <p>You agree to indemnify and hold LSC and its subsidiaries and affiliates harmless from and against any and all liabilities, damages, losses or costs, including without limitation, attorneys' fees and costs, incurred in connection with any claim directly or indirectly arising out of or related to your participation in the Program or any breach by you of these Terms and Conditions. LSC reserves the right, at its own expense, to assume the exclusive defense and control of any matter subject to indemnification hereunder. You further agree to cooperate as requested by LSC in the defense of any claim. You shall not settle any claim subject to indemnification without the written consent of LSC.&nbsp; By participating in the Program, you release LSC and its subsidiaries and affiliates from any claims, liabilities, damages, losses or costs that may arise from your participation in the Program.&nbsp; In the event that any taxes are payable, you agree to pay such taxes and to indemnify and hold LSC and its subsidiaries and affiliates harmless from any such taxes.</p>
            
            <p><strong>ARBITRATION AGREEMENT - READ THIS CAREFULLY</strong></p>
            
            <p>LSC and you agree to<b>ARBITRATE</b>all disputes and claims between us arising out of or in any way relating to: a) the Program; b) your participation in the Program; or 3) these Terms and Conditions, including any claims regarding the validity, existence, binding effect, interpretation, performance, breach or termination of these Term and Conditions, whether such claims are based in contract, tort, statute, fraud, misrepresentation or any other legal theory.</p>
            
            <p>By entering into this Agreement, you and LSC agree that each is<b>waiving the right to a trial by jury</b>, to the fullest extent permitted by applicable law.</p>
            
            <p><b>You and LSC agree that each may bring claims against the other only in your or its INDIVIDUAL CAPACITY, and NOT AS A PLAINTIFF, REPRESENTATIVE OR CLASS MEMBER IN ANY PUPORTED CLASS ACTION OR REPRESENTAITVE PROCEEDING, AND NOT IN ANY PRIVATE ATTORNEY GENERAL CAPACITY.</b>&nbsp; Further, unless both you and LSC agree otherwise, the arbitrator may not consolidate more than one person's claims, and may not otherwise preside over any form of a representative or class proceeding.&nbsp; The arbitrator may award injunctive relief only in favor of the individual party seeking relief and only to the extent necessary to provide relief warranted by that party's individual claim.&nbsp; If this specific provision is found to be unenforceable, then the entirety of this arbitration provision shall be null and void.</p>
            
            <p>All arbitrations under this Agreement will be governed by the Commercial Dispute Resolution Procedures and the Supplementary Procedures for Consumer Related Disputes (collectively, "AAA Rules") of the American Arbitration Association ("AAA"), as modified by this Agreement, and will be administered by the AAA.&nbsp; The AAA Rules are available online at<a href="http://www.adr.org/">www.adr.org</a>or by calling the AAA at 1-800-778-7819.&nbsp; All issues are for the arbitrator to decide, including the scope of this arbitration provision, but the arbitrator is bound by the terms of this Agreement.</p>
            
            <p>Unless LSC and you agree otherwise, any arbitration hearings will take place in the county (or parish) of your billing address.&nbsp; If you file a claim, we agree that you may choose whether the arbitration will be conducted solely on the basis of documents submitted to the arbitrator, through a telephonic hearing, or by an in-person hearing as established by the AAA Rules.&nbsp;</p>
            
            <p>A party who intends to seek arbitration must first send to the other, by certified mail, a written Notice of Dispute ("Notice"). The Notice to LSC should be sent to: Legal Department, LSC, at the email address of:&nbsp; <a href="mailto:chad@lifestories.com">chad@lifestories.com</a> ("Notice Address''). The Notice must (a) describe the nature and basis of the claim or dispute; and (b) set forth the specific relief sought ("Demand").&nbsp; If LSC and you do not reach an agreement to resolve the claim within 30 days after the Notice is received, you or LSC may commence an arbitration proceeding.&nbsp; During the arbitration, the amount of any settlement offer made by LSC or you shall not be disclosed to the arbitrator until after the arbitrator determines the amount, if any, to which you or LSC are entitled.&nbsp;</p>
            
            <p>After LSC receives notice at the Notice Address that you have commenced arbitration, it will promptly reimburse you for your payment of the filing fee.&nbsp; If you are unable to pay this fee, LSC will pay it directly upon receiving a written request at the Notice Address.&nbsp; Except as otherwise provided for herein, LSC will pay all AAA filing, administration, and arbitrator fees for any arbitration initiated in accordance with the notice requirements above.&nbsp; If, however, the arbitrator finds that either the substance of your claim or the relief sought in the Demand is frivolous or brought for an improper purpose (as measured by the standards set forth in Federal Rule of Civil Procedure 11(b)), then the payment of all such fees will be governed by the AAA Rules.&nbsp; In such case, you agree to reimburse LSC for all monies previously disbursed by it that are otherwise your obligation to pay under the AAA Rules.</p>
            
            <p>The arbitrator may make rulings and resolve disputes as to the payment and reimbursement of fees, expenses, and the premium and the attorney premium at any time during the proceeding and upon request from either party made within 14 days of the arbitrator's ruling on the merits.&nbsp; The right to attorneys' fees and expenses supplements any such rights you may have under applicable law, except that you may not recover any duplicative awards of attorneys' fees or expenses.</p>
            
            <p>Notwithstanding any provision in this Agreement to the contrary, we agree that if we make any change to this arbitration provision (other than a change to the Notice Address), you may reject any such change and require LSC to adhere to the language in this provision if a dispute between us arises.</p>
            
            <p>All references in these Terms and Conditions to "LSC," "we, "us," "you," and "Member" include our respective subsidiaries, affiliates, agents, employees, predecessors in interest, successors, and assigns, as well as all authorized or unauthorized users or beneficiaries of products or services under this or prior agreements between us.</p>
            
            <p>This Agreement evidences a transaction in interstate commerce, and thus the Federal Arbitration Act governs the interpretation and enforcement of this provision. This arbitration provision shall survive termination of this Agreement.</p>

        </div>
    
        <div class="column33">
            <?php $theme->load('sidebar'); ?>
        </div>
    
    </div>
    </div>
    
</div>

<?php $theme->load('footer'); ?>